# This is the numpy exercise


####  Import the numpy package under the name `np`

In [2]:
import numpy as np

####  Create a null vector of size 10

In [3]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

####  Create a null vector of size 10 but the fifth value which is 1

In [4]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


####  Create a vector with values ranging from 10 to 49

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

####  Reverse a vector (first element becomes last)

In [6]:
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


####  Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####  Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

####  Create a 3x3 identity matrix

In [9]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  Create a 3x3x3 array with random values

In [10]:
np.random.random((3,3,3))

array([[[0.41119546, 0.91262427, 0.45945793],
        [0.71693104, 0.59296511, 0.7339471 ],
        [0.95727893, 0.92174658, 0.65841467]],

       [[0.06588772, 0.10922521, 0.09354989],
        [0.7065297 , 0.01468497, 0.74796417],
        [0.24148147, 0.48860998, 0.96003734]],

       [[0.47339865, 0.45758534, 0.44485404],
        [0.71047077, 0.86890615, 0.01914871],
        [0.87692548, 0.63291415, 0.48651714]]])

####  Create a 10x10 array with random values and find the minimum and maximum values



In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00556035125483445 0.9891829927298593


####  Create a random vector of size 30 and find the mean value

In [12]:
np.random.random(30).mean()


0.5167761231718501

####  Create a 2d array with 1 on the border and 0 inside



In [13]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


####  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [14]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


####  Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [15]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
